# Generated by Django 3.2.7 on 2021-10-05 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('place_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('formatted_address', models.TextField()),
                ('locality', models.CharField(max_length=80)),
                ('adm_area_lv2', models.CharField(max_length=80)),
                ('adm_area_lv1', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.IntegerField(null=True)),
                ('mapa', models.ImageField(upload_to='trips')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destino', to='trips.ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origen', to='trips.ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
