# Generated by Django 3.2.7 on 2021-10-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
