# Generated by Django 3.2.6 on 2021-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='mapa',
            field=models.ImageField(null=True, upload_to='trips'),
        ),
    ]
