# Generated by Django 3.2.6 on 2021-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='polyline',
            field=models.TextField(null=True),
        ),
    ]
