# Generated by Django 3.2.6 on 2021-10-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_ubicacion_polyline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='polyline',
        ),
        migrations.AddField(
            model_name='trip',
            name='polyline',
            field=models.TextField(null=True),
        ),
    ]
