# Generated by Django 3.2.6 on 2021-10-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20211005_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='locality',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
