# Generated by Django 3.2.6 on 2021-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_ubicacion_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='adm_area_lv1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='adm_area_lv2',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
